name: buildandtest

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release 
        dotnet publish -c Release -o myapp/ 
      
    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: QDevTestApp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
        package: myapp/
 
